name: Pipelines Demo
on: [push]
jobs:
  Trigger-Reimage-Pipeline:
    environment: gh-action-demo
    runs-on: ubuntu-latest
    steps:
      - name: Reimage Pipeline Trigger
        env:
          PIPELINE_SECRET: ${{ secrets.PIPELINE_SECRET}}
          PIPELINE_URL: ${{ secrets.PIPELINE_URL }}
        run: |
          curl $PIPELINE_URL \
            -H "Content-Type: application/json" \
            -d "{ \"secret\": \"$PIPELINE_SECRET\"}" \
            -X POST
